export const GET_NOTE = 'GET_NOTE'
export const GET_NOTE_SUCCEEDED = 'GET_NOTE_SUCCEEDED'
export const GET_NOTE_FAILED = 'GET_NOTE_FAILED'

export const ADD_NOTE = 'ADD_NOTE'
export const ADD_NOTE_SUCCEEDED = 'ADD_NOTE_SUCCEEDED'
export const ADD_NOTE_FAILED = 'ADD_NOTE_FAILED'

export const MOD_NOTE = 'MOD_NOTE'
export const MOD_NOTE_SUCCEEDED = 'MOD_NOTE_SUCCEEDED'
export const MOD_NOTE_FAILED = 'MOD_NOTE_FAILED'

export const DEL_NOTE = 'DEL_NOTE'
export const DEL_NOTE_SUCCEEDED = 'DEL_NOTE_SUCCEEDED'
export const DEL_NOTE_FAILED = 'DEL_NOTE_FAILED'

export const UPDATE_SSR_NOTE = 'UPDATE_SSR_NOTE'

export const SEARCH_NOTE = 'SEARCH_NOTE'
export const SEARCH_NOTE_SUCCEEDED = 'SEARCH_NOTE_SUCCEEDED'
export const SEARCH_NOTE_FAILED = 'SEARCH_NOTE_FAILED'

export const BATCH_DEL_NOTE = 'BATCH_DEL_NOTE'
export const BATCH_DEL_NOTE_SUCCEEDED = 'BATCH_DEL_NOTE_SUCCEEDED'
export const BATCH_DEL_NOTE_FAILED = 'BATCH_DEL_NOTE_FAILED'